source :rubygems

gem 'sinatra', :require => 'sinatra/base'
gem 'haml'
gem 'thin'
gem 'shotgun'
gem 'gist'
gem 'mingle4r'
gem 'jenkins-remote-api'
gem 'rspec'
gem 'cucumber'
gem 'watir-webdriver'
gem 'taza', :git => 'git://github.com/hammernight/taza.git'
gem 'headless'
gem 'capistrano'